const body=document.body, nav=document.getElementById('navLinks'), menu=document.getElementById('menuBtn'), theme=document.getElementById('themeBtn');
menu.addEventListener('click',()=>nav.classList.toggle('open'));
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
theme.addEventListener('click',()=>{body.classList.toggle('dark');theme.textContent=body.classList.contains('dark')?'☾':'☀';localStorage.setItem('theme',body.classList.contains('dark')?'dark':'light')});
if(localStorage.getItem('theme')==='dark'){body.classList.add('dark');theme.textContent='☾'}
const phrases=['Machine Learning Enthusiast','Computer Vision Learner','Data Analytics Explorer','AI/ML Engineer in Progress'];let pi=0,ci=0,del=false;const typed=document.getElementById('typed');
function type(){const word=phrases[pi];typed.textContent=del?word.slice(0,--ci):word.slice(0,++ci);if(!del&&ci===word.length){del=true;setTimeout(type,1100);return}if(del&&ci===0){del=false;pi=(pi+1)%phrases.length}setTimeout(type,del?45:85)}type();
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const progress=document.getElementById('progress'),topBtn=document.getElementById('topBtn'),navbar=document.getElementById('navbar');window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/max*100)+'%';topBtn.classList.toggle('show',scrollY>500);navbar.classList.toggle('scrolled',scrollY>20)});topBtn.onclick=()=>scrollTo({top:0,behavior:'smooth'});
const lightbox=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImg'),lbTitle=document.getElementById('lightboxTitle');document.querySelectorAll('.certificate').forEach(card=>card.addEventListener('click',()=>{lbImg.src=card.dataset.img;lbTitle.textContent=card.dataset.title;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}));function closeBox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');lbImg.src=''}document.getElementById('closeBox').onclick=closeBox;lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeBox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBox()});
const canvas=document.getElementById('particles'),ctx=canvas.getContext('2d');let dots=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;dots=Array.from({length:Math.min(65,Math.floor(innerWidth/18))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.6+.4,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18}))}function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=body.classList.contains('dark')?'rgba(180,190,255,.35)':'rgba(80,70,160,.18)';dots.forEach(d=>{d.x+=d.vx;d.y+=d.vy;if(d.x<0||d.x>canvas.width)d.vx*=-1;if(d.y<0||d.y>canvas.height)d.vy*=-1;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(animate)}resize();addEventListener('resize',resize);animate();
